---
title: "Final Project"
author: "The Outliers"
date: "2025-04-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, results='hold')
```

# Data Loading and Cleaning
```{r, include=FALSE}
#change path specific to your computer
csv_path <-"//Users/alishali/Library/CloudStorage/GoogleDrive-al138@wellesley.edu/.shortcut-targets-by-id/1MhR7KDrJwhRpHYUrEblfKMUqoQeo74PH/STAT228_FinalProject/rawDataset.csv"
```

```{r}
raw <- read.csv(csv_path, header=TRUE)
raw$Hand
data.rp <- raw[raw$Hand == "R" & raw$Grip=="P",]

#Remove irrelevant information and sparse predictors
rp.lessCols <- data.rp[, !(names(data.rp) %in% c("Hand", "Grip", "Date", "Name", "Club.Team", "Height", "D.Defense", "Defense.TS", "TR.Defense", "Exchange TS", "Exchange.TS", "TR.Exchange", "Infighting.TS", "TR.Infighting", "Hand.TS", "TR.Hand", "my.side.TS", "my.side.D", "my.side.TR", "middle.TS", "middle.D", "middle.TR", "their.side.TS", "their.side.D", "their.side.TR", "Result"))]
#Note that we no longer needed Hand and Grip since we already filtered for all RP


#rename predictors to a standard format
names(rp.lessCols)[names(rp.lessCols) == "D.CounterA"] <- "CounterA.D"
names(rp.lessCols)[names(rp.lessCols) == "TR.CounterA"] <- "CounterA.TR"
names(rp.lessCols)[names(rp.lessCols) == "P.Riposte..D..TS"] <- "RiposteDef.TS"
names(rp.lessCols)[names(rp.lessCols) == "D.P.Riposte"] <- "RiposteDef.D"
names(rp.lessCols)[names(rp.lessCols) == "TR.P.Riposte.D."] <- "RiposteDef.TR"
names(rp.lessCols)[names(rp.lessCols) == "P.Riposte..A..TS"] <- "RiposteAtt.TS"
names(rp.lessCols)[names(rp.lessCols) == "D.P.Riposte..A."] <- "RiposteAtt.D"
names(rp.lessCols)[names(rp.lessCols) == "TR.P.Riposte..A."] <- "RiposteAtt.TR"
names(rp.lessCols)[names(rp.lessCols) == "Caught..H..TR"] <- "CaughtH.TR"
names(rp.lessCols)[names(rp.lessCols) == "Caught..B..TR"] <- "CaughtB.TR"
names(rp.lessCols)[names(rp.lessCols) == "Caught..T..TR"] <- "CaughtT.TR"
names(rp.lessCols)[names(rp.lessCols) == "X6.2..D..TS"] <- "62Def.TS"
names(rp.lessCols)[names(rp.lessCols) == "TR.6.2..D."] <- "62Def.TR"
names(rp.lessCols)[names(rp.lessCols) == "X6.2..A..TS"] <- "62Att.TS"
names(rp.lessCols)[names(rp.lessCols) == "D.6.2.A."] <- "62Att.D"
names(rp.lessCols)[names(rp.lessCols) == "TR"] <- "62Att.TR"
names(rp.lessCols)[names(rp.lessCols) == "Lunge..T..TS"] <- "LungeT.TS"
names(rp.lessCols)[names(rp.lessCols) == "D.Lunge.T."] <- "LungeT.D"
names(rp.lessCols)[names(rp.lessCols) == "TR.Lunge..T."] <- "LungeT.TR"
names(rp.lessCols)[names(rp.lessCols) == "Lunge.L..TS"] <- "LungeL.TS"
names(rp.lessCols)[names(rp.lessCols) == "TR.1"] <- "LungeL.TR"
names(rp.lessCols)[names(rp.lessCols) == "Lunge..B..TS"] <- "LungeB.TS"
names(rp.lessCols)[names(rp.lessCols) == "D.Lunge.B."] <- "LungeB.D"
names(rp.lessCols)[names(rp.lessCols) == "TR.2"] <- "LungeB.TR"
names(rp.lessCols)[names(rp.lessCols) == "Jump.Lunge.TS"] <- "JumpLunge.TS"
names(rp.lessCols)[names(rp.lessCols) == "D.Jump.Lunge"] <- "JumpLunge.D"
names(rp.lessCols)[names(rp.lessCols) == "TR.Jump.Lunge"] <- "JumpLunge.TR"
names(rp.lessCols)[names(rp.lessCols) == "Adv..Lunge.TS"] <- "AdvLunge.TS"
names(rp.lessCols)[names(rp.lessCols) == "D.Adv..Lunge"] <- "AdvLunge.D"
names(rp.lessCols)[names(rp.lessCols) == "TR.Adv..Lunge"] <- "AdvLunge.TR"
names(rp.lessCols)[names(rp.lessCols) == "D.Fleche"] <- "Fleche.D"
names(rp.lessCols)[names(rp.lessCols) == "TR.Fleche"] <- "Fleche.TR"
names(rp.lessCols)[names(rp.lessCols) == "Prep.to.guard.TS"] <- "PrepGuard.TS"
names(rp.lessCols)[names(rp.lessCols) == "TR.Prep.to.guard"] <- "PrepGuard.TR"
names(rp.lessCols)[names(rp.lessCols) == "D.Squat"] <- "Squat.D"
names(rp.lessCols)[names(rp.lessCols) == "TR.Squat"] <- "Squat.TR"

#NA = 0
rp.lessCols[is.na(rp.lessCols)] <- 0

cols <- names(rp.lessCols)

# Remove suffix like ".TS", ".TR", ".D"
cleanedActions <- gsub("\\.(TS|TR|D)$", "", cols)          # remove suffix
# Get unique base action names
baseActions <- unique(cleanedActions)
baseActions 

df <- rp.lessCols

for (a in baseActions) {
  ts <- paste0(a, ".TS")
  tr <- paste0(a, ".TR")
  d  <- paste0(a, ".D")

  present <- c(ts, tr, d) %in% names(df)
  if (any(present)) {
    ts_val <- if (ts %in% names(df)) as.numeric(df[[ts]]) else 0
    tr_val <- if (tr %in% names(df)) as.numeric(df[[tr]]) else 0
    d_val  <- if (d  %in% names(df)) as.numeric(df[[d]])  else 0

    df[[paste0(a, "_Exec")]] <- ts_val + tr_val + d_val
  }
}


# Net outcome = total TS - total TR
ts_total <- rowSums(df[, grep("\\.TS$", names(df))], na.rm = TRUE)
tr_total <- rowSums(df[, grep("\\.TR$", names(df))], na.rm = TRUE)
df$netoutcome <- ts_total - tr_total

39
clean <- df[,40:56]

```

#Assumptions
```{r}
plot(lm.obj)
```



```{r}
lm.obj <- lm(netoutcome~., data = clean)
summary(lm.obj)

#AIC
step(lm.obj, direction="both",trace=0, steps=1000, k=2)

n <- nrow(clean)
#BIC
step(lm.obj, direction="both",trace=0, steps=1000, k=log(n))

#All-Subset
library(glmulti)
library(leaps)

mm <- model.matrix(netoutcome ~ ., data = clean)

# 2. drop the "(Intercept)" column
xMat <- mm[, -1]

leaps(x=xMat, y=clean$netoutcome, method="adjr2", nbest=10)
glmulti(lm.obj, method='h', crit="aic")xmail
```


